// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4D9P6h8KUR_498bKg2zyCICfvsKL6Co',
    appId: '1:191749596959:web:e51cf5f1cc25109a4c322a',
    messagingSenderId: '191749596959',
    projectId: 'task-management-7056d',
    authDomain: 'task-management-7056d.firebaseapp.com',
    storageBucket: 'task-management-7056d.firebasestorage.app',
    measurementId: 'G-Y3DWV73D2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-QDIQkrUen3sWrAuU320yEN0OvmHLkFI',
    appId: '1:191749596959:android:bb4eae6f431686b84c322a',
    messagingSenderId: '191749596959',
    projectId: 'task-management-7056d',
    storageBucket: 'task-management-7056d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOaYlSdhyJABXLz3gGrz7JOMhhU533XU8',
    appId: '1:191749596959:ios:8a89ee484207f9994c322a',
    messagingSenderId: '191749596959',
    projectId: 'task-management-7056d',
    storageBucket: 'task-management-7056d.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH4D9P6h8KUR_498bKg2zyCICfvsKL6Co',
    appId: '1:191749596959:web:7bef6323304a650f4c322a',
    messagingSenderId: '191749596959',
    projectId: 'task-management-7056d',
    authDomain: 'task-management-7056d.firebaseapp.com',
    storageBucket: 'task-management-7056d.firebasestorage.app',
    measurementId: 'G-53TEQ7931Q',
  );
}
